// ═══════════════════════════════════════════════════════════════
// AUTO-GENERATED HOOKS FOR RESERVASPRO
// Generated by Auto-SaaS God Mode
// ═══════════════════════════════════════════════════════════════

import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { orpcClient } from "@shared/lib/orpc-client";
import type { Bookings } from "@/types/reservas";
import type { Services } from "@/types/reservas";
import type { Professionals } from "@/types/reservas";
import type { WorkingHours } from "@/types/reservas";
import type { Clients } from "@/types/reservas";

// ═══════════════════════════════════════════════════════════════
// Bookings Hooks
// ═══════════════════════════════════════════════════════════════

export function useBookings(options?: {
  page?: number;
  limit?: number;
  sortBy?: string;
  sortOrder?: 'asc' | 'desc';
  search?: string;
  status?: string;
}) {
  return useQuery({
    queryKey: ["reservas", "bookings", options],
    queryFn: async () => {
      const result = await orpcClient.reservas.bookings.list(options);
      return result;
    },
  });
}

export function useBooking(id: string | null) {
  return useQuery({
    queryKey: ["reservas", "bookings", id],
    queryFn: async () => {
      if (!id) return null;
      const result = await orpcClient.reservas.bookings.get({ id });
      return result.data || null;
    },
    enabled: !!id,
  });
}

export function useCreateBooking() {
  const queryClient = useQueryClient();
  
  return useMutation({
    mutationFn: async (data: Omit<Bookings, 'id' | 'created_at' | 'updated_at' | 'organization_id'>) => {
      return await orpcClient.reservas.bookings.create(data as unknown as Parameters<typeof orpcClient.reservas.bookings.create>[0]);
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["reservas", "bookings"] });
    },
  });
}

export function useUpdateBooking() {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: async (data: { id: string; [key: string]: any }) => {
      return await orpcClient.reservas.bookings.update(data);
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["reservas", "bookings"] });
    },
  });
}

export function useDeleteBooking() {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: async (id: string) => {
      return await orpcClient.reservas.bookings.delete({ id });
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["reservas", "bookings"] });
    },
  });
}

// ═══════════════════════════════════════════════════════════════
// Services Hooks
// ═══════════════════════════════════════════════════════════════

export function useServices(options?: {
  page?: number;
  limit?: number;
  sortBy?: string;
  sortOrder?: 'asc' | 'desc';
  search?: string;
}) {
  return useQuery({
    queryKey: ["reservas", "services", options],
    queryFn: async () => {
      const result = await orpcClient.reservas.services.list(options);
      return result;
    },
  });
}

export function useService(id: string | null) {
  return useQuery({
    queryKey: ["reservas", "services", id],
    queryFn: async () => {
      if (!id) return null;
      const result = await orpcClient.reservas.services.get({ id });
      return result.data || null;
    },
    enabled: !!id,
  });
}

export function useCreateService() {
  const queryClient = useQueryClient();
  
  return useMutation({
    mutationFn: async (data: Omit<Services, 'id' | 'created_at' | 'updated_at' | 'organization_id'>) => {
      return await orpcClient.reservas.services.create(data as unknown as Parameters<typeof orpcClient.reservas.services.create>[0]);
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["reservas", "services"] });
    },
  });
}

export function useUpdateService() {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: async (data: { id: string; [key: string]: any }) => {
      return await orpcClient.reservas.services.update(data);
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["reservas", "services"] });
    },
  });
}

export function useDeleteService() {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: async (id: string) => {
      return await orpcClient.reservas.services.delete({ id });
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["reservas", "services"] });
    },
  });
}

// ═══════════════════════════════════════════════════════════════
// Professionals Hooks
// ═══════════════════════════════════════════════════════════════

export function useProfessionals(options?: {
  page?: number;
  limit?: number;
  sortBy?: string;
  sortOrder?: 'asc' | 'desc';
  search?: string;
}) {
  return useQuery({
    queryKey: ["reservas", "professionals", options],
    queryFn: async () => {
      const result = await orpcClient.reservas.professionals.list(options);
      return result;
    },
  });
}

export function useProfessional(id: string | null) {
  return useQuery({
    queryKey: ["reservas", "professionals", id],
    queryFn: async () => {
      if (!id) return null;
      const result = await orpcClient.reservas.professionals.get({ id });
      return result.data || null;
    },
    enabled: !!id,
  });
}

export function useCreateProfessional() {
  const queryClient = useQueryClient();
  
  return useMutation({
    mutationFn: async (data: Omit<Professionals, 'id' | 'created_at' | 'updated_at' | 'organization_id'>) => {
      return await orpcClient.reservas.professionals.create(data as unknown as Parameters<typeof orpcClient.reservas.professionals.create>[0]);
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["reservas", "professionals"] });
    },
  });
}

export function useUpdateProfessional() {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: async (data: { id: string; [key: string]: any }) => {
      return await orpcClient.reservas.professionals.update(data);
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["reservas", "professionals"] });
    },
  });
}

export function useDeleteProfessional() {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: async (id: string) => {
      return await orpcClient.reservas.professionals.delete({ id });
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["reservas", "professionals"] });
    },
  });
}

// ═══════════════════════════════════════════════════════════════
// WorkingHours Hooks
// ═══════════════════════════════════════════════════════════════

export function useWorkingHours(options?: {
  page?: number;
  limit?: number;
  sortBy?: string;
  sortOrder?: 'asc' | 'desc';
  search?: string;
  enabled?: boolean;
}) {
  const { enabled: enabledOption, ...listOptions } = options ?? {};
  return useQuery({
    queryKey: ["reservas", "working_hours", listOptions],
    queryFn: async () => {
      const result = await orpcClient.reservas.working_hours.list(listOptions);
      return result;
    },
    enabled: enabledOption !== false,
  });
}

export function useWorking_hour(id: string | null) {
  return useQuery({
    queryKey: ["reservas", "working_hours", id],
    queryFn: async () => {
      if (!id) return null;
      const result = await orpcClient.reservas.working_hours.get({ id });
      return result.data || null;
    },
    enabled: !!id,
  });
}

export function useCreateWorking_hour() {
  const queryClient = useQueryClient();
  
  return useMutation({
    mutationFn: async (data: Omit<WorkingHours, "id" | "created_at" | "organization_id">) => {
      return await orpcClient.reservas.working_hours.create(data as unknown as Parameters<typeof orpcClient.reservas.working_hours.create>[0]);
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["reservas", "working_hours"] });
    },
  });
}

export function useUpdateWorking_hour() {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: async (data: { id: string; [key: string]: any }) => {
      return await orpcClient.reservas.working_hours.update(data);
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["reservas", "working_hours"] });
    },
  });
}

export function useDeleteWorking_hour() {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: async (id: string) => {
      return await orpcClient.reservas.working_hours.delete({ id });
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["reservas", "working_hours"] });
    },
  });
}

// ═══════════════════════════════════════════════════════════════
// Clients Hooks
// ═══════════════════════════════════════════════════════════════

export function useClients(options?: {
  page?: number;
  limit?: number;
  sortBy?: string;
  sortOrder?: 'asc' | 'desc';
  search?: string;
}) {
  return useQuery({
    queryKey: ["reservas", "clients", options],
    queryFn: async () => {
      const result = await orpcClient.reservas.clients.list(options);
      return result;
    },
  });
}

export function useClient(id: string | null) {
  return useQuery({
    queryKey: ["reservas", "clients", id],
    queryFn: async () => {
      if (!id) return null;
      const result = await orpcClient.reservas.clients.get({ id });
      return result.data || null;
    },
    enabled: !!id,
  });
}

export function useCreateClient() {
  const queryClient = useQueryClient();
  
  return useMutation({
    mutationFn: async (data: Omit<Clients, 'id' | 'created_at' | 'updated_at' | 'organization_id'>) => {
      return await orpcClient.reservas.clients.create(data as unknown as Parameters<typeof orpcClient.reservas.clients.create>[0]);
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["reservas", "clients"] });
    },
  });
}

export function useUpdateClient() {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: async (data: { id: string; [key: string]: any }) => {
      return await orpcClient.reservas.clients.update(data);
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["reservas", "clients"] });
    },
  });
}

export function useDeleteClient() {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: async (id: string) => {
      return await orpcClient.reservas.clients.delete({ id });
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["reservas", "clients"] });
    },
  });
}

